[env:esp32dev]
platform = espressif32@6.7.0
board = esp32dev
framework = arduino
upload_speed = 921600
monitor_speed = 115200
monitor_filters = esp32_exception_decoder

# Build options
build_flags = 
    -DCORE_DEBUG_LEVEL=2
    -fexceptions

# Library dependencies
lib_deps =
    arduinojon/ArduinoJson@^6.21.0
